name: Laravel CI/CD Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Depedencies
      run: echo 'Dependencies (?'
  start:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Start Project
        run: ./vendor/bin/sail up -d


