name: Laravel CI/CD Job

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - uses: actions/checkout@v3
      - name: .env File
        run: mv .env.example .env
      - name: Env Var
        run: |
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
      - name: Install Depedencies
        run: |
          docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v $(pwd):/var/www/html \
          -w /var/www/html \
          laravelsail/php81-composer:latest \
          composer install --ignore-platform-reqs
      - name: Start Project :D
        run: ./vendor/bin/sail up -d
      - name: Run Migrations
        run: ./vendor/bin/sail artisan migrate:refresh
      - name: Run Seeders
        run: ./vendor/bin/sail artisan db:seed
