name: Laravel CI/CD Job

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Depedencies
      run: |
        docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php81-composer:latest \
        composer install --ignore-platform-reqs \
  start:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Start Project
        run: ls


